db/sqldb.go
main_test.go

Uh oh! Realized that some SQL tests were actually failing secretly, because we haven't set them up properly on Travis. This should fix them.
#39 should prevent things like this from happening in the future. For now, I should remember to swap out `MemDatabase` with `SQLDatabase` in `main_test` when testing/reviewing PRs and my own changes, as well as running `go test ./db`.

fix(tests): when run with SQL database, tests were failing

---

.env.example
api.go
db/db.go
main.go
main_test.go

fixes #43. made a new issue for blacklisting IPs, since it'll be more involved (this would have to happen after the MX host lookup in the checker).
Also moved `godotenv` to `main.go` since we're using env vars in `api` as well as `db` now.

feat(api): domain dont-scan list

---

.travis.yml
api.go
main.go
main_test.go
policy/policy.go

Fixes #25.
Added a subpackage, `policy`, meant to handle parsing and regularly updating an in-memory representation of the TLS policy list. If it gets really large, we'll maybe want to persist this cache somehow, but for now this is alright.
`UpdatedList` wraps the actual List and performs periodic (hourly) fetches to it.
It isn't currently extensively used in the server code, but will be once we start using this machine to run periodic scans and to roll new changes to the policy list.
The other large change is the introduction of `policyCheck` in `api.go`. This isn't exactly where this function belongs, but it'll do for now since it relies on both `db` (to check if a domain has been queued but not on the list) and `policy` (to check if a domain has been added).

/api/scan returns policy JSON

---

main.go
main_test.go

I looked into rate limiting a bit and it looks like rolling our own wouldn't be too hard, but involves a fair amount of code (eg final example in https://www.alexedwards.net/blog/how-to-rate-limit-http-requests), so i went with the [tollbooth](https://github.com/didip/tollbooth) package.
After integrating it, I realized this package only allows us to specify a maximum number of requests per second. It seems like we might want to permit certain actions less frequently than once/second/ip. I think that will require a different solution. We could use this in the meantime.

Rate limit by IP

---

api.go
db/memdb.go
db/sqldb.go
main.go
policy/policy.go

Use lowercase letters for error messages, also tweaked the wording a teeny bit for consistency
Closes #34

Format error strings

---

.travis.yml
checker/README.md
checker/check.go
checker/cmd/starttls-check/cmd.go
checker/domain.go
checker/hostname.go
checker/hostname_test.go

Basically following [these instructions](https://saintgimp.org/2013/01/22/merging-two-git-repositories-into-one-repository-without-losing-file-history/) - no fancy subtrees or submodules, I just merged 'em :metal: 
IMO this resolves #75 
Will follow up with a PR that renames starttls-scanner to starttls-backend once this is merged.
Interestingly, the checker failed to advertise the ciphersuites listed in [checker issue 30](https://github.com/EFForg/starttls-check/issues/30) in https://travis-ci.com/EFForg/starttls-scanner/builds/81079716. I bumped the Go version to 1.10 and it passes. Will create a ticket to bump to the Go version in the Dockerfile.
When this is ready for merge, please merge this one without squashing so we can keep that sweet commit history :)

Merge checker repo into scanner

---

email_test.go

small fix that was causing some trouble on my local setup. Thought it'd be nice to have the test not rely on the system env configuration, since it's a unit-test. @vbrown608 does this look ok to you?

fix(test): TestRequireEnvConfig is more reliable

---

checker/domain.go
checker/domain_test.go
checker/hostname.go
checker/hostname_test.go

fixes #105 
> 
> The current version of this tool checks that the presented cert is valid for at least one of the names specified in `mx-hostnames`.
> 
> The new validation rules specify that:
> 1. The selected MX host matches at least one of the `mx-hostnames` patterns, and that
> 2. The presented certificate is valid for the hostname.
> 
I had to move the `mxHostnames` (which I renamed `expectedHostnames` in some parts of the code, to be slightly more clear) check to the domain-level check! Which also involved writing tests for `domain.go`.
Two notes:
- I did a little bit of refactoring in `domain.go` so we could test it sanely.
- This changes the API, as I noted in issue #105. It's not a big change, but we should use it to talk about how we want to roll out API changes in general :)

validation rules match MTA-STS

---

checker/hostname_test.go

fixes #114 forever.
more permanent than fix in #115; however #115 can (and should be) landed ASAP. this should undergo more thorough review.
`createCert` scraped pieces from [crypto/tls/generate_cert.go](http://golang.org/src/pkg/crypto/tls/generate_cert.go) and [`X509KeyPair`](https://golang.org/src/crypto/tls/tls.go?s=5915:5986#L183) from the same package. I'm being sloppy with the DER <-> PEM parsing errors since it's a test fn and it's deterministic; but let me know if you'd prefer we forward them to a `t.Fatal`.

testfix: regen checker cert for each test run

---

.env.example
.env.test.example
db/db.go
db/scripts/init_tables.sql
db/sqldb.go
db/sqldb_test.go
email.go
email_test.go
main.go

Handles AWS Simple Email Service (SES) bounces and complaints submitted to a webhook via AWS Simple Notification Service (SNS).
Rather than verifying the signature ([something like this](https://github.com/robbiet480/go.sns/blob/master/main.go#L45-L91)) I'm checking for an API key set on SNS notification. That's how we're handling things in the Action Center and I think it's adequate for email bounce/complaint handling but let me know if you'd rather do the full verification.
Separately, we'll need to configure SNS to send notifications with the API key to this endpoint and set that key in the production env.

Handle SES bounce and complaint notifications

---

api.go
list_api.go
list_api_test.go
main.go
main_test.go
policy/policy.go
policy/policy_test.go

fixes #123 
`/auth/list` works and has been tested ~now need to finish testing `/auth/sync`.~
EDIT: Decided to fix this up to only include the `/auth/list` endpoint. `/auth/sync` will come in a future PR.
Sub-part of #6

Authed endpoint for retrieving list

---

list_api.go
list_api_test.go
main.go

fixes #122. depends on #118. subpart of #6.
thinking to rename rename `list_api` to `auth_api`
Adds two new endpoints under `auth`: `promote` and `fail`.
`promote` auto-promotes any entries in the DB which are already on the list.
`fail` fails a specified domain.

list mgmt: fail/promote domains

---

db/Dockerfile

Most recent staging deployment can't start the database: `The data directory was initialized by PostgreSQL version 10, which is not compatible with this version 11.1`

Pin postgres dependency version

---

checker/hostname_test.go

The purpose of this test is to demonstrate that the checker successfully initiates and SMTP connection with mail servers that use delayed greeting (eg http://www.deer-run.com/~hal/sysadmin/greet_pause.html). 
Closes #102

Test checker connection with delayed greeting

---

checker/cache.go
db/sqldb.go
db/sqldb_test.go

We weren't serializing the timestamp into the correct place, so the cache kept expiring.

fix hostname scan caching

---

checker/domain_test.go
checker/hostname.go
checker/hostname_test.go

That is, patterns like ".example.com" match the same way
as "*.example.com". This is important just to match the original
policy matching rules, so we get fewer false negatives
while running list validations.

Wildcard matching works without an asterisk label

---

checker/domain.go
checker/hostname.go
checker/mta_sts.go
checker/mta_sts_test.go
checker/result.go

Include MTA-STS policy and mode and domain result so we can render that info.
I realized a weird thing about implementing `MarshalJSON` for `Result` - since `Result` is embedded in `MTASTSResult` (and `HostnameResult`), those types also use `Result`'s overridden `MarshalJSON` and lose their additional fields :upside_down_face:. I fixed that by implementing it directly on `MTASTSResult` as well. I think that extra strings that get added to the `Result` JSON are useful for debugging (I always forget the status mappings when I'm working on the frontend) but I'd also be fine with simplifying things by getting rid of them now that we're keeping the longer strings in Hugo.

Include extra MTA-STS info in domain result

---

api.go
main_test.go
models/domain.go
models/domain_test.go
policy/policy.go

Now that we have models, moving some queue logic out of the handler. I also added some helpers for common `APIResponse` status codes to make the handler a bit easier to scan.
This is preparation for checking hostnames or MTA-STS success in #146.

Queueability to model

---

checker/mta_sts.go

* "testing" and "enforce" mode now cause warning (previously success).
* Since we're displaying these warning/failure messages directly on the client, I made them a little prettier.

Better MTA-STS errors

---

api.go
checker/domain.go
checker/domain_test.go
checker/hostname.go
checker/hostname_test.go
checker/mta_sts.go
checker/mta_sts_test.go
main_test.go
models/domain.go
models/domain_test.go
models/scan.go
queue_test.go
scan_test.go

Depends on #187 
Closes #146 
Two possible success paths:
1) they check the MTA-STS box and their most recent scan was successful with a successful MTA-STS check
- In this case we can use the `PreferredHostnames` from their scan, which must be a subset of the hostnames listed in their MTA-STS policy file.
2) they provide hostnames, their most recent scan was successful, and the hostnames they provided are a subset of the `PreferredHostnames` in their scan.

Accept MTA-STS boolean or check hostnames match

---

.travis.yml
db/db.go
db/scripts/init_tables.sql
db/sqldb.go
db/sqldb_test.go
models/timeseries.go

I got a bit nerd sniped trying to write this as a single query! I think it's fine for now and if we want to prune scans at some point we can write some aggregated stats to the DB.
Postgres returns timestamps with a zero offset from UTC and no timezone (since UTC isn't the only timezone with that offset, it doesn't want to assume). I'm giving it an explicit "UTC" timezone for easier to comparison. I considered converting to local time, but that would mess with the idea of which events occured on which date, which was calculated in the database with a zero offset from UTC.
I think we should cache this, since the result will almost always be close enough. We could probably set a header in the handler and then cache the whole response using nginx (my preference) or use a simple in-memory …

Store and retrieve stats for user scans

---

checker/cache.go
checker/checker.go
checker/domain.go
checker/hostname.go
validator/validate.go

* Add a mutex to the cache
* Don't lazy init the cache on the checker. Unfortunately I don't think there's a way to do this that won't cause a race, short of adding a mutex to the checker. Since we're actually only using the default in one place I just made the default be no cache and created the cache explicitly there.
Also, the tests you wrote for checking domains helped me find a major bug just as I was getting ready to open this! Thank you :D

Make hostname result cache safe for concurrent use

---

main.go
models/scan.go

So long as the policy itself does validate, even if it's in testing mode, let's allow folks to queue their domains.
The only two types of failures where a "Warning" would be returned are for "testing" mode and when the content type isn't `text/plain`.

Can queue MTA-STS domain with "Warning" notice

---

checker/Dockerfile
checker/totals.go

Depends on #206 
I decided to give the checker its own Dockerfile because it builds a different binary and could have different dependencies. We could build two binaries in the existing Dockerfile but it seemed more consistent with the Docker philosophy to have a single-application image.
This can run daily scans with a `checker/docker-compose.yml` like 
```
services:
app:
build: .
environment:
- CONNECTION_POOL_SIZE=32
volumes:
- ./shared:/shared
command: /bin/sh -c 'env >> /etc/environment && crontab /shared/check.cron && crond -f'
```
and a `checker/shared/check.cron` like
```
0 15 * * * /go/bin/starttls-check --file=/shared/majestic_million.csv --column=2 --aggregate=true >> /shared/stats.csv
```
I'd like to commit those to a deploy repo managed by techops.

Dockerfile for checker

---

main_test.go
policy/policy.go

These fields were deprecated from the list a while ago.

Remove references to unused fields

---

.env.example
checker/cmd/starttls-check/cmd.go
checker/cmd/starttls-check/cmd_test.go
checker/totals.go
db/db.go
db/sqldb.go
main.go
stats/import.go
stats/import_test.go

* Import stats from our scans of the web!
* I switched this communicate via JSON rather than a CSV, since Go's built-in handling of JSON is so much better. The main drawback is that it's not possible to maintain a valid JSON list by simply appending lines of new data to the end. I'm going to try to handle that with a little bit of sed magic in the cron job on the stats server.

Import stats as JSON

---

stats/stats.go
stats/stats_test.go

Expect JSON lines (http://jsonlines.org/) format for incoming aggregated scan data. This makes it much easier to append log lines when running scans.

Use JSONL format for aggregated scans

---

checker/totals.go

When conducting an aggregated scan, we need to increment the totals of domains in mta-sts testing and enforce mode.

Bugfix: increment MTA-STS totals

---

checker/totals.go
db/sqldb.go
db/sqldb_test.go
stats/stats.go
stats_test.go

* Serve domain count rather than percent for top-million scan
* Serve data to chart as a json array of x-y coordinates, sorted along the x axis

Format stats for frontend

---

checker/totals.go
db/db.go
db/sqldb.go
db/sqldb_test.go
main.go
stats/stats.go
stats/stats_test.go
stats_test.go

Rather than using a fancy query to pull stats over a rolling window from the DB, this PR adds a DB fn to query stats for a single 14-day window from the db and write them to an aggregated stats table. We can then access them from the aggregated stats table the same way we access aggregated stats from our scans of the top million domains.
Fixes #235
Depends on #237

235 simplify stats query

---

api/stats_test.go
db/sqldb.go

The source for stats (local vs the top domains list) was getting lost when reading from the db, which prevented the app from show a raw total for the MTA-STS adoption from the top million.

Read stats source from db
