EFForg/starttls-backend

- main.go
Straight from the example of https://golang.org/pkg/net/http/#Server.Shutdown
Closes #14
> Shutdown server on interrupt

- api.go
- main_test.go
fixes #41 
kinda simple, but works...
> feat(api): return cache of recent scans

- .env.example
- api.go
- email.go
- main.go
- main_test.go
Fixes #32.
Adds a bunch more environment variables too! Yay email \o/
@vbrown608 if you'd like to test, I can give you the creds.
> Email validation

- email.go
> fix(validation email): should send now

- api.go
- main_test.go
- util.go
> Validate hostnames and ensure scans during queuing

- api.go
- main_test.go
> Filter empty hostnames from request

- db/sqldb.go
- email.go
- email_test.go
- main.go
- main_test.go
- util.go
> fix(email): enable multiple types of authentication

- checker/domain.go
- db/sqldb.go
- db/sqldb_test.go
- main.go
- policy/policy.go
- policy/policy_test.go
- validator/validate.go
fixes #70, new & updated version of #72 
let's have the server do this so i can stop doing this manually \o/
> Server validates entries in the background

- README.md
- db/db.go
- db/scripts/init_tables.sql
- db/sqldb.go
- db/sqldb_test.go
Part 1/2 of #6. Splitting up #71.
When we land this, we have to make sure to migrate DBs on the prod containers! How to do this is outlined in `README.md`.
> Add last-updated field to domains table

- checker/domain.go
- checker/hostname.go
We've talked about doing this briefly but haven't done it yet. Since @vbrown608 landed the fix that bumps the # of connections from 7 to 2, I feel more comfortable doing this now.
> bump connection timeout

- main.go
> Reduce fatality of not being able to connect to mailserver

- api.go
- checker/cmd/starttls-check/cmd.go
- checker/domain.go
- checker/domain_test.go
- checker/hostname.go
- checker/hostname_test.go
- main.go
- validator/validate.go
- validator/validate_test.go
> Validator fixes

- api.go
- queue_test.go
> Don't requeue domains already on the policy list

- email.go
Also, rawSNSMessage just forces a string to conform the the interface required to capture a message using Raven. I changed it to something more generic to reflect that.
> Send unparseable SNS notification body to Sentry

- README.md
> document blacklist

- api.go
- checker/cache.go
- checker/cache_test.go
- checker/cmd/starttls-check/cmd.go
- checker/domain.go
- checker/domain_test.go
- checker/hostname.go
- db/db.go
- db/scripts/init_tables.sql
- db/sqldb.go
- db/sqldb_test.go
- policy/policy_test.go
- validator/validate.go
- validator/validate_test.go
fixes #130 
Not sure that this is implemented at the correct layer. May pull functionality from DB and into another interface that sits on top of it.
> Caching hostname results

- .env.example
- Dockerfile
- README.md
- docker-compose.yml
- entrypoint.sh
fixes #149 
@vbrown608 does this resemble what you were talking about? i cribbed a bunch of the stuff from SEC's setup :)
> perform outstanding DB migrations when starting up docker container

- checker/mta_sts_test.go
Depends on #153 - is this what you had in mind @sydneyli ?
>  Check UTF-8 support for policy file

- main.go
:arrow_up: :arrow_up: :arrow_up:
> Raise queue limit to 20/hour

- api.go
- checker/mta_sts.go
> Enable MTA-STS check and hide full TCP error from endpoint

- checker/mta_sts.go
> Fix MTA-STS content type check

- checker/mta_sts.go
- checker/mta_sts_test.go
> Bump up severity of MTA-STS hostname mismatch to Failure

- main.go
- stats.go
- stats_test.go
> Serve MTA-STS stats

- checker/checker.go
- checker/domain.go
- checker/domain_test.go
- checker/hostname.go
- checker/mta_sts.go
> Mock MTA-STS check

- api.go
- db/scripts/init_tables.sql
- db/sqldb.go
- models/domain.go
- queue_test.go
Part 3 of #207
How many weeks do you want to "test" your domain for?
well now you can tell us and we'll remember it forever.
Doesn't actually do anything with the number yet.
> Read & store "weeks" parameter

- checker/mta_sts.go
Incorporates suggestions from @Snawoot on https://github.com/EFForg/starttls-backend/pull/153
Fixes #206
> Timeout all the things

- .travis.yml
Suggested [here](https://github.com/EFForg/starttls-backend/pull/227#discussion_r282681337).
> Repeat DB migration on travis to ensure script is idempotent

- README.md
- checker/domain.go
Fixes #219.
While writing this, I think we should audit and clean up our API responses as well as documenting them, probably as a part of #199!
> Document sample API responses
